export enum PermissionEnum {
    // Post Management
    POST_CREATE = "POST_CREATE",
    POST_UPDATE = "POST_UPDATE",
    POST_DELETE = "POST_DELETE",
    POST_VIEW = "POST_VIEW",

    // Course Management
    COURSE_CREATE = "COURSE_CREATE",
    COURSE_UPDATE = "COURSE_UPDATE",
    COURSE_DELETE = "COURSE_DELETE",
    COURSE_VIEW = "COURSE_VIEW",

    // System Management
    USER_MANAGE = "USER_MANAGE",
    SYSTEM_CONFIG = "SYSTEM_CONFIG",
    CACHE_MANAGE = "CACHE_MANAGE",

    // Quiz Management
    QUIZ_MANAGE = "QUIZ_MANAGE",
    QUIZ_CREATE = "QUIZ_CREATE",
    QUIZ_UPDATE = "QUIZ_UPDATE",
    QUIZ_DELETE = "QUIZ_DELETE",

    // Exercise Management
    EXERCISE_MANAGE = "EXERCISE_MANAGE",
    EXERCISE_CREATE = "EXERCISE_CREATE",
    EXERCISE_UPDATE = "EXERCISE_UPDATE",
    EXERCISE_DELETE = "EXERCISE_DELETE",

    // For Students
    QUIZ_TAKE = "QUIZ_TAKE",
    EXERCISE_SUBMIT = "EXERCISE_SUBMIT",
}
